const gis = {
    title: 'GIS Certification',
    pageTitle: 'GIS Certificate Program',
    slug: 'gis',
    order: 2,
    startdate: 'January 7, 2024',
    header: 'Certificate Course in Geographical Information System (GIS)',
    description: 'Emerging technologies such as GIS (Geographic Information System) and RS (Remote Sensing) are instrumental in addressing intricate global challenges and impacting various aspects of life. In this context, the role of a Geospatial expert is gaining significance in the decision-making process. Acquiring practical knowledge is essential to comprehensively grasp the underlying concepts and unlock the potential for innovative applications of these technologies across diverse domains.',
    whatsapp: 'https://chat.whatsapp.com/FRmZTHwsDLACdxUAQOg3GE',
    formLink: 'https://forms.gle/2KLbzK9qmT7mr59j7',
    aboutHead: 'Covers pretty much everything you need to know about GIS',
    detailsPara: 'The course is uniquely designed by top technical experts to ensure the meaningful skill development which enables the candidates to gain insight about technology and make them ready to start/accelerate their carrier immediately after completing this course. The objective of the course is to develop an understanding and competence in, Geo spatial technology as- ',
    details: [
      "Digitization of maps and different themes for present day landform evaluation.",
      "Calculation of the area, perimeter and other domains for estimation of different layers for integration and decision making capacity.",
      "Auto Generation of hydrological parameters for water related processes.",
      "Use of various statistical methods in GIS for spatial and vector data.",
      "Application of GIS in various disciplines of geography, geology, social sciences, civil works, etc.",
      "Relevant for disciplines like Science, Social Science, Humanities, Archeology, Disaster Management, Engineering, Computer Science, Planning and Architechture, Mining, Agriculture, Population Studies, Medical Science etc."
    ],
    dayPlan: [
      {
        daycount: "Day 1",
        Chapter: "Introduction to GIS",
        duration: "1 hours 30 minutes",
        date: "2/10/2023",
        day: "Monday",
        Chapterdes: "Overview, A Brief History of GIS, Essential Components of GIS, Software Installation",
      },
      {
        daycount: "Day 2",
        Chapter: "GIS Basics I",
        duration: "1 hours 30 minutes",
        date: "4/10/2023",
        day: "Wednesday",
        Chapterdes: "GIS System, Projection System, Hands on Practice",
      },
      {
        daycount: "Day 3",
        Chapter: "GIS Basics II",
        duration: "1 hours 30 minutes",
        date: "6/10/2023",
        day: "Friday",
        Chapterdes: "Geodatabase Preparation, Type of GIS Layers, Hands on Practice",
      },
      {
        daycount: "Day 4",
        Chapter: "GIS Basics III",
        duration: "1 hours 30 minutes",
        date: "9/10/2023",
        day: "Monday",
        Chapterdes: "Georeferencing of Vector, Georeferencing of Raster, Projection Transformation, Hands on Practice",
      },
      {
        daycount: "Day 5",
        Chapter: "GIS Layer Editing",
        duration: "1 hours 30 minutes",
        date: "11/10/2023",
        day: "Wednesday",
        Chapterdes: "Digitisation of Point, Line and Polygon, Filling Attributes, Attribute Joining, Area and Perimeter Calculation, Calculations in Attributes, Hands on Practice",
      },
      {
        daycount: "Day 6",
        Chapter: "Data Management Tools",
        duration: "1 hours 30 minutes",
        date: "13/10/2023",
        day: "Friday",
        Chapterdes: "Vector Operations in GIS Platform, ArcGIS-Clip Management and Mosaic, Raster and Vector Data Clipping, Making Sample Location with GPS Location, Hands on Practice",
      },
      {
        daycount: "Day 7",
        Chapter: "Spatial Analyst I",
        duration: "1 hours 30 minutes",
        date: "16/10/2023",
        day: "Monday",
        Chapterdes: "Extraction by points, Extraction by mask, Maths tools, Reclassify, Hands on Practice",
      },
      {
        daycount: "Day 8",
        Chapter: "Spatial Analyst II",
        duration: "1 hours 30 minutes",
        date: "18/10/2023",
        day: "Wednesday",
        Chapterdes: "Condition, Interpolation, Hands on Practice",
      },
      {
        daycount: "Day 9",
        Chapter: "Spatial Analyst III",
        duration: "1 hours 30 minutes",
        date: "20/10/2023",
        day: "Friday",
        Chapterdes: "Hydrology Tool, Raster Calculator, Hands on Practice",
      },
      {
        daycount: "Day 10",
        Chapter: "Spatial Analyst IV",
        duration: "1 hours 30 minutes",
        date: "23/10/2023",
        day: "Monday",
        Chapterdes: "Zonal Stats, Table Calculation, Rater & Vector Analysis, Hands on Practice",
      },
      {
        daycount: "Day 11",
        Chapter: "Use cases of tools",
        duration: "1 hours 30 minutes",
        date: "25/10/2023",
        day: "Wednesday",
        Chapterdes: "Watershed analysis, Contour preparation, Slope, Aspect and Hill Shade analysis, Hands on Practice",
      },
      {
        daycount: "Day 12",
        Chapter: "Query Builder",
        duration: "1 hours 30 minutes",
        date: "27/10/2023",
        day: "Friday",
        Chapterdes: "Query Algorithm, Writing an equation, Hands on Practice",
      },
      {
        daycount: "Day 13",
        Chapter: "Hands on Practise of Vector Analysis",
        duration: "1 hours 30 minutes",
        date: "30/10/2023",
        day: "Monday",
        Chapterdes: "Case Study for LULC Change",
      },
      {
        daycount: "Day 14",
        Chapter: "Hands on Practise of Raster Analysis",
        duration: "1 hours 30 minutes",
        date: "1/11/2023",
        day: "Wednesday",
        Chapterdes: "Case study for Change Detection",
      },
      {
        daycount: "Day 15",
        Chapter: "Map Preparation and Data Export",
        duration: "1 hours 30 minutes",
        date: "3/11/2023",
        day: "Friday",
        Chapterdes: "Scale Fixing, North Direction, Annotation, Exporting Map, Hands on Practice",
      },
      {
        daycount: "Day 16",
        Chapter: "GIS Open-Source Platform",
        duration: "1 hours 30 minutes",
        date: "6/11/2023",
        day: "Monday",
        Chapterdes: "Q GIS, Vector Operation, Raster Operation, GIS analysis, Map Preparation, Hands on Practice",
      },
    ],

    duration: '6 Weeks',
    numberOfLiveClasses: 18,
    numberOfAssignments: '6+',
    projectsIncluded: 'Hands-on Projects',
    additionalInfo: 'Lecture timings will be decided as per your availability',
    price: '₹3,540',
    originalPrice: '₹7,000',
    discount: '50%',
    inclusiveOfGST: true,
    image: "globe.jpg",
    
    // lecturesPerWeek: 2,
    begining: "Course starts",
    contact: 9450906849,
    durationLine:"Course Duration",
    liveLine:"Live Lectures",
    assignmentsLine: "Hands-on Assignments",
    registerBtn: "Register Now",
    courseLine: "This course is a balance of lectures & practicals",

    infoPoints: [
      "6 Weeks","18 Live Classes","3 Lectuers Per Week","6+ Assignments","Hands-on Projects", 
    ],

  };
  
  export default gis;