const remote = {
    title: 'Remote Sensing Certification',
    pageTitle: 'Remote Sensing Course',
    slug: 'remote-sensing',
    startdate: 'December 25, 2023',
    header: 'Certificate Course in Remote Sensing',
    description: "The Certificate Course in Remote Sensing offers a comprehensive training program, covering essential principles of remote sensing and hands-on experience with relevant software. This course provides practical skills in image processing, classification, and spatial modeling, enabling participants to harness the power of remote sensing data for environmental monitoring, resource management, and GIS applications. ",
    whatsapp: 'https://chat.whatsapp.com/C1JrWWEMrbwBp785QnFNVj',
    formLink: 'https://forms.gle/4XCdgsjLha6iwnga8',
    aboutHead: 'Covers pretty much everything you need to know about Remote Sensing',
    detailsPara: 'The Remote Sensing Certification Course offers a comprehensive exploration of remote sensing principles and practical applications using relevant software. Beginning with foundational concepts, participants learn satellite image processing techniques, image classification, and analysis methodologies. Advanced technologies, including LiDAR and hyperspectral data, are covered alongside real-world use cases and applications of UAVs in remote sensing. Hands-on practice sessions reinforce theoretical knowledge, preparing participants for certification through a structured curriculum. Topics include:',
    details: [
      "Satellite Image Processing: FCC preparation, image referencing, and enhancement.",
      "Image Classification and Analysis: Digital classification, supervised/unsupervised classification, and on-screen visual interpretation.",
      "Advanced Technologies: Delve into LiDAR, microwave, and hyperspectral data, understanding their applications and advancements.",
      "Real-world Use Cases: Examine practical applications through case studies, highlighting the versatility of remote sensing technologies.",
      "Practical Hands-on Practice: Engage in extensive hands-on sessions, reinforcing skills in utilizing software for practical applications.",         
  ],
    dayPlan : [
      {
        daycount: "Day 1",
        Chapter: "Introduction to Remote Sensing: A Short History of Remote Sensing; Introduction to Digital Data; Important Basic Concepts of Remote Sensing; Geographic Concepts",
        duration: "1 hour 30 minutes",
        date: "25/12/2023",
        day: "Monday",
      },
      {
        daycount: "Day 2",
        Chapter: "Satellite Image Technology and Basics: The Electromagnetic Spectrum; Passive/Active Sensors; Remote Sensing Sensor Platforms; Analogue Aerial Photography; Digital Imagery; Imagery Types",
        duration: "1 hour 30 minutes",
        date: "29/12/2023",
        day: "Friday",
      },
      {
        daycount: "Day 3",
        Chapter: "Image Processing Software Installation Demo",
        duration: "1 hour 30 minutes",
        date: "1/01/2024",
        day: "Monday",
      },
      {
        daycount: "Day 4",
        Chapter: "Satellite Image Pre Processing-I: Satellite Data Downloading; FCC Preparation; Colour Matching; Hands on Practice",
        duration: "1 hour 30 minutes",
        date: "5/01/2024",
        day: "Friday",
      },
      {
        daycount: "Day 5",
        Chapter: "Satellite Image Pre Processing-II: Image Pre-Processing; Hands on Practice",
        duration: "1 hour 30 minutes",
        date: "8/01/2024",
        day: "Monday",
      },
      {
        daycount: "Day 6",
        Chapter: "Satellite Image Pre Processing-III: Image Referencing and Transformation; Image Mosaics; Hands on Practice",
        duration: "1 hour 30 minutes",
        date: "12/01/2024",
        day: "Friday",
      },
      {
        daycount: "Day 7",
        Chapter: "Hands on Practice for Satellite Image Pre Processing",
        duration: "1 hour 30 minutes",
        date: "15/01/2024",
        day: "Monday",
      },
      {
        daycount: "Day 8",
        Chapter: "Image Processing-I: Image Enhancement; Hands on Practice",
        duration: "1 hour 30 minutes",
        date: "19/01/2024",
        day: "Friday",
      },
      {
        daycount: "Day 9",
        Chapter: "Image Processing-II: Image Fusion; Hands on Practice",
        duration: "1 hour 30 minutes",
        date: "22/01/2024",
        day: "Monday",
      },
      {
        daycount: "Day 10",
        Chapter: "Image Classification-I: General Introduction; Vector File Creation; Raster File Creation; Hands on Practice",
        duration: "1 hour 30 minutes",
        date: "26/01/2024",
        day: "Friday",
      },
      {
        daycount: "Day 11",
        Chapter: "Image Classification-II: Digital Classification; Image Classification Unsupervised; Image Classification Supervised; Hands on Practice",
        duration: "1 hour 30 minutes",
        date: "29/01/2024",
        day: "Monday",
      },
      {
        daycount: "Day 12",
        Chapter: "Image Classification-III: On Screen Visual Interpretation; Change Detection; Vegetation Indices Analysis; Hands on Practice",
        duration: "1 hour 30 minutes",
        date: "2/02/2024",
        day: "Friday",
      },
      {
        daycount: "Day 13",
        Chapter: "Hands on Practice for Image Classification",
        duration: "1 hour 30 minutes",
        date: "5/02/2024",
        day: "Monday",
      },
      {
        daycount: "Day 14",
        Chapter: "Satellite Image Analysis-I: Attribute Formation; Colour Coding; Hands on Practice",
        duration: "1 hour 30 minutes",
        date: "9/02/2024",
        day: "Friday",
      },
      {
        daycount: "Day 15",
        Chapter: "Satellite Image Analysis-II: Area Calculation; Statistics Generation",
        duration: "1 hour 30 minutes",
        date: "12/02/2024",
        day: "Monday",
      },
      {
        daycount: "Day 16",
        Chapter: "Advanced Technology of Remote Sensing: Brief Description of Optical, Microwave, LiDAR & Hyperspectral Data; Advancement of Mivrowave, LiDAR and Hyperspectral on Optical Data; Use Cases of Various Aspects of Remote Sensing; UAV (Unmanned Aerial Vehicle)",
        duration: "1 hour 30 minutes",
        date: "16/02/2024",
        day: "Friday",
      },
    ],
  

    duration: '8 Weeks',
    numberOfLiveClasses: 16,
    numberOfAssignments: '8+',
    projectsIncluded: 'Hands-on Projects',
    additionalInfo: 'Lecture timings will be decided as per your availability',
    price: '₹2,990',
    originalPrice: '₹10,700',
    discount: '72%',
    inclusiveOfGST: true,
    image: "satellite.avif",
    
    // lecturesPerWeek: 2,
    begining: "Course starts",
    contact: 9450906849,
    durationLine:"Course Duration",
    liveLine:"Live Lectures",
    assignmentsLine: "Hands-on Assignments",
    registerBtn: "Register Now",
    courseLine: "This course is a balance of lectures & practicals",

    infoPoints: [
      "6 Weeks","18 Live Classes","3 Lectuers Per Week","6+ Assignments","Hands-on Projects", 
    ],
  };

export default remote;